# Generated by Django 6.0.6 on 2026-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='observacao',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
