# Generated by Django 6.0.6 on 2026-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_notafiscal_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='loja',
            field=models.CharField(choices=[('canguaretama', 'Canguaretama'), ('pipa', 'Praia de Pipa'), ('gostoso', 'São Miguel do Gostoso')], default='canguaretama', max_length=20),
        ),
    ]
