# Generated by Django 6.0.6 on 2026-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_notafiscal_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='loja',
            field=models.CharField(choices=[('canguaretama', 'Canguaretama'), ('praia_de_pipia', 'Praia de Pipa'), ('sao_miguel_do_gostoso', 'São Miguel do Gostoso')], default='canguaretama', max_length=50),
        ),
    ]
