# Generated by Django 6.0.6 on 2026-06-23 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_alter_notafiscal_loja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='observacao_resposta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='observacao_resposta_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='observacao_resposta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respostas_observacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
